"""
Symbol translation between Binance format (BTCUSDT) and bare HL name (BTC).

Mapping is built from hl_symbol_map.json, which is generated by matching
HL instrument names against the Binance historical store (strip USDT suffix).
"""

import json
from pathlib import Path

_MAP_FILE = Path(__file__).parent / "hl_symbol_map.json"

with _MAP_FILE.open() as _f:
    _data = json.load(_f)

_binance_to_hl: dict[str, str] = _data["binance_to_hl"]
_hl_to_binance: dict[str, str] = _data["hl_to_binance"]


def to_hl(binance_symbol: str) -> str | None:
    """BTCUSDT → BTC. Returns None if not in the HL universe."""
    return _binance_to_hl.get(binance_symbol)


def to_binance(hl_name: str) -> str | None:
    """BTC → BTCUSDT. Returns None if no Binance data exists for this HL coin."""
    return _hl_to_binance.get(hl_name)
