"""
Symbol translation between Binance USDT-M perp format (BTCUSDT) and bare HL name (BTC).

Mapping is loaded from hl_symbol_map.json, regenerated by build_symbol_map.py. For
high-supply meme tokens the two exchanges use different 1000× notations — HL k-prefix
vs Binance 1000-prefix — so KPEPE ⇄ 1000PEPEUSDT (not KPEPEUSDT). The k prefix is not
always a multiplier (KAITO, KAS are literal names), so the generator resolves each
candidate against the live perp set rather than rewriting prefixes blindly.
"""

import json
from pathlib import Path

_MAP_FILE = Path(__file__).parent / "hl_symbol_map.json"

with _MAP_FILE.open() as _f:
    _data = json.load(_f)

_binance_to_hl: dict[str, str] = _data["binance_to_hl"]
_hl_to_binance: dict[str, str] = _data["hl_to_binance"]


def to_hl(binance_symbol: str) -> str | None:
    """BTCUSDT → BTC. Returns None if not in the HL universe."""
    return _binance_to_hl.get(binance_symbol)


def to_binance(hl_name: str) -> str | None:
    """BTC → BTCUSDT. Returns None if no Binance data exists for this HL coin."""
    return _hl_to_binance.get(hl_name)
